# Android fstab file.
# <src>						<mnt_point>   <type>  <mnt_flags and options>  <fs_mgr_flags>
# The filesystem that contains the filesystem checker binary (typically /system) cannot
# specify MF_CHECK, and must come before any filesystems that do specify MF_CHECK
/dev/block/platform/soc/11230000.mmc/by-name/userdata     /data         f2fs      noatime,nosuid,nodev,discard,reserve_root=32768,fsync_mode=nobarrier       wait,check,quota,formattable,reservedsize=32M
/dev/block/platform/soc/11230000.mmc/by-name/persist      /mnt/vendor/persist     ext4    noatime,nosuid,nodev,barrier=1,data=ordered,nodelalloc,errors=panic   wait,check,formattable
/dev/block/platform/soc/11230000.mmc/by-name/misc         /misc         emmc      defaults                                                                   defaults
system                                                    /system       ext4      noatime,ro,errors=panic                                                    wait,slotselect,logical,first_stage_mount
vendor                                                    /vendor       ext4      noatime,ro,errors=panic                                                    wait,slotselect,logical,first_stage_mount
*/block/sd*                                               auto          auto      defaults                                                                   voldmanaged=usb:auto,noemulatedsd
